### ISSUE TITLE
Large binaries in step 04

### ISSUE THREAD

**Issue by yoghurt-x86** [haydenridd/stm32-zig-porting-guide#4]
Going from step 03 to step 04 significantly increase the binary files.

Here's how the output looks after i build: 
```
$ ls -lh 03_with_zig_build/zig-out/bin/
total 952K
-rw-r--r-- 1 yoggi users 5.8K Oct 28 21:42 blinky.bin
-rwxr-xr-x 1 yoggi users 922K Oct 28 21:42 blinky.elf
-rw-r--r-- 1 yoggi users  17K Oct 28 21:42 blinky.hex
```
```
$ ls -lh 04_advanced_zig_project/zig-out/bin/
total 2.0M
-rw-r--r-- 1 yoggi users 393K Oct 28 21:43 blinky.bin
-rwxr-xr-x 1 yoggi users 997K Oct 28 21:43 blinky.elf
-rw-r--r-- 1 yoggi users 567K Oct 28 21:43 blinky.hex
```

If you compare the hex files from 03 and 04. it's increased from 17k to 567k.

**Comment by haydenridd** [comment]
Yup, you are indeed correct! It's because sadly trying to use Zig's `addObject()` to neatly package ST's HAL into a module is flawed, as it will bring in ALL their code and not strip out unused functions. I'm just going to have to re-tool step 04 to use a different method, and I'll close this issue once I do.

**Comment by haydenridd** [comment]
Closing due to:
https://github.com/haydenridd/stm32-zig-porting-guide/commit/8cb391cd4084754fbe6cd017969d62c908529938

Fixing this issue!
